apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: webscanner

build:
  artifacts:
    - image: web-scan-crawler
      context: crawler
      docker:
        dockerfile: Dockerfile.dev
    - image: web-scan-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
    - image: web-scan-email
      context: email
      docker:
        dockerfile: Dockerfile
    - image: web-scan-orm
      context: orm
      docker:
        dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: webscanner
        chartPath: helm/webscanner
        createNamespace: true
        namespace: web-scanner-dev
        valuesFiles:
          - helm/webscanner/values-dev.yaml
        setValueTemplates:
          frontend.image.tag: "{{.IMAGE_TAG_web_scan_frontend}}"
          frontend.image.repository: "{{.IMAGE_REPO_web_scan_frontend}}"

profiles:
  - name: prod
    build:
      local:
        push: false
      artifacts:
        - image: web-scan-crawler
          context: crawler
          docker:
            dockerfile: Dockerfile
        - image: web-scan-frontend
          context: frontend
          docker:
            dockerfile: Dockerfile
        - image: web-scan-email
          context: email
          docker:
            dockerfile: Dockerfile
    deploy:
      helm:
        releases:
          - name: webscanner
            chartPath: helm/webscanner
            createNamespace: true
            namespace: web-scanner-prod
            valuesFiles:
              - helm/webscanner/values.yaml