FROM node:24-alpine AS builder
WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

FROM node:24-alpine
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]